# -*- coding: utf-8 -*-
"""Lista2_PAI-Segmentacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-dhIEtAGRbo81iguM3nD4X4QXgVJekI

Imports basicos
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

"""Funcoes auxiliares"""

def aplicar_otsu(img):
  otsu = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
  return otsu

def aplicar_kmeans(img, k=2):
  Z = img.reshape((-1, 1))
  Z = np.float32(Z)
  criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
  ret, label, center = cv2.kmeans(Z, k, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
  center = np.uint8(center)
  res = center[label.flatten()]
  segmented = res.reshape((img.shape))
  return segmented

def mostrar_resultados(titulo, original, otsu, kmeans,k):

    original = np.array(original)
    otsu = np.array(otsu)
    kmeans = np.array(kmeans)


    if original.ndim == 3:
        original = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)
    if otsu.ndim == 3:
        otsu = cv2.cvtColor(otsu, cv2.COLOR_BGR2GRAY)
    if kmeans.ndim == 3:
        kmeans = cv2.cvtColor(kmeans, cv2.COLOR_BGR2GRAY)

    plt.figure(figsize=(14, 5))
    plt.suptitle(titulo, fontsize=14)

    plt.subplot(1, 3, 1)
    plt.imshow(original, cmap='gray')
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(otsu, cmap='gray')
    plt.title('Otsu')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(kmeans, cmap='gray')
    plt.title('K-Means')
    plt.axis('off')

    plt.show()

    # Salva resultados
    #cv2.imwrite(f'./data/outputs/{nome}_otsu.png', otsu)
    cv2.imwrite(f'./data/outputs/{nome}_kmeans{k}.png', kmeans)


"""carregar imagens"""

industrial = cv2.imread('./data/imgs/industrial.jpg', cv2.IMREAD_GRAYSCALE)
medical = cv2.imread('./data/imgs/medical.jpg', cv2.IMREAD_GRAYSCALE)
natural = cv2.imread('./data/imgs/natural.jpg', cv2.IMREAD_GRAYSCALE)

"""Aplicar metodos"""
k = 4  # Numero de clusters para K-Means
for nome, img in [('Industrial', industrial), ('Medica', medical), ('Natural', natural)]:
  # Extrai a imagem binarizada do resultado de aplicar_otsu
  _, otsu_img = aplicar_otsu(img)
  kmeans = aplicar_kmeans(img, k)
  # Passa a imagem binarizada para a função mostrar_resultados
  mostrar_resultados(f'Segmentacao - {nome}', img, otsu_img, kmeans, k)